### ISSUE TITLE
Read instance for LogFloat

### ISSUE THREAD

**Issue by zaxtax** [wrengr/logfloat#5]
It would be nice if there was a Read instance for LogFloat. As a first pass I have the following:

````haskell
instance Read LogFloat where
    readsPrec p s = [(logFloat x, r) | (x, r) <- readsPrec p s]
````

**Comment by wrengr** [comment]
I just pushed 5f5150362ddaacf96910a4ccdcb8699a9ed137ea which does this more safely (i.e., without `logFloat` throwing an error). Test it out and make sure it works for you, then I'll publish it to Hackage

**Comment by zaxtax** [comment]
Works for me!

**Comment by wrengr** [comment]
FWIW, I'm going to try to get the `Vector` instances put in before I publish it. Feel free to harass me if it's not done by next weekend.

**Comment by zaxtax** [comment]
Interesting, what made you decide to include them?

**Comment by zaxtax** [comment]
Is the `Vector` instance stuff happening?
